import java.util.Properties

fun readSdkDir(propertiesFile: File): String? {
    if (!propertiesFile.isFile) return null

    return Properties()
        .apply { propertiesFile.inputStream().use(::load) }
        .getProperty("sdk.dir")
        ?.trim()
        ?.takeIf { it.isNotEmpty() }
}

fun escapeLocalPropertiesPath(path: String): String =
    path.replace("\\", "\\\\")

val localPropertiesFile = file("local.properties")
if (!localPropertiesFile.isFile) {
    val sdkDir = sequenceOf(
        System.getenv("ANDROID_HOME"),
        System.getenv("ANDROID_SDK_ROOT"),
        readSdkDir(file("../local.properties")),
        System.getenv("LOCALAPPDATA")?.let { "$it\\Android\\Sdk" },
        System.getenv("HOME")?.let { "$it/Library/Android/sdk" },
        System.getenv("HOME")?.let { "$it/Android/Sdk" },
    )
        .filterNotNull()
        .firstOrNull { File(it).isDirectory }

    if (sdkDir != null) {
        localPropertiesFile.writeText(
            """
            |# Generated by Gradle from the multi-repo Android SDK configuration.
            |# This file is intentionally ignored by git.
            |sdk.dir=${escapeLocalPropertiesPath(sdkDir)}
            |
            """.trimMargin(),
        )
    }
}

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "MobileSingleKotlin"
include(":app")
